import { NextResponse } from "next/server";
import { firebaseWebConfig } from "@/lib/firebase/config";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

/**
 * The messaging service worker, generated rather than checked in as a static
 * file so the Firebase config comes from the environment.
 *
 * Without it Firebase can only show notifications while a tab is open — which
 * is why background pushes never arrived before.
 */
export async function GET() {
  const body = `/* Generated by /firebase-messaging-sw.js/route.ts */
importScripts("https://www.gstatic.com/firebasejs/12.18.0/firebase-app-compat.js");
importScripts("https://www.gstatic.com/firebasejs/12.18.0/firebase-messaging-compat.js");

firebase.initializeApp(${JSON.stringify(firebaseWebConfig)});

const messaging = firebase.messaging();

messaging.onBackgroundMessage(function (payload) {
  const title =
    (payload.notification && payload.notification.title) ||
    (payload.data && payload.data.title) ||
    "Bonus Academy";
  const body =
    (payload.notification && payload.notification.body) ||
    (payload.data && payload.data.body) ||
    "";
  const link =
    (payload.fcmOptions && payload.fcmOptions.link) ||
    (payload.data && payload.data.url) ||
    "/";
  self.registration.showNotification(title, {
    body: body,
    icon: "/icon.png",
    badge: "/icon.png",
    data: { url: link },
  });
});

self.addEventListener("notificationclick", function (event) {
  event.notification.close();
  const url = (event.notification.data && event.notification.data.url) || "/";
  event.waitUntil(
    self.clients.matchAll({ type: "window", includeUncontrolled: true }).then(function (list) {
      for (const client of list) {
        if (client.url.startsWith(self.location.origin) && "focus" in client) {
          client.navigate(url);
          return client.focus();
        }
      }
      return self.clients.openWindow(url);
    }),
  );
});
`;

  return new NextResponse(body, {
    headers: {
      "Content-Type": "application/javascript; charset=utf-8",
      "Cache-Control": "no-store",
    },
  });
}
